export const CARDS = [
    {
        name: 'Ученики',
        description: 'Управление данными учеников',
        id: 1,
        link: '/students',
        accessedRoles: ['admin', 'coach'],
        image: "images/Students.png",
        dataTestId: "students-card",
    },
    {
        name: 'Расписание',
        description: 'Просмотр расписания занятий.',
        id: 2,
        link: '/timetable',
        accessedRoles: ['admin', 'coach', 'student', 'parent'],
        image: "images/Timetable.png",
        dataTestId: "timetable-card",
    },
    {
        name: 'Задачи',
        description: 'Шахматные задачи на тактику и стратегию',
        id: 3,
        link: '/tasks',
        accessedRoles: ['admin', 'coach', 'student'],
        image: "images/Tasks.png",
        dataTestId: "tasks-card",
    },
    {
        name: 'Отчеты',
        description: 'Генерация отчетов по ученикам и тренерам',
        id: 4,
        link: '/reports',
        accessedRoles: ['admin', 'coach'],
        image: "images/Reports.png",
        dataTestId: "reports-card",
    },
    {
        name: 'Дебюты',
        description: 'База дебютов для партий',
        id: 5,
        link: '/chess-openings',
        accessedRoles: ['admin', 'coach'],
        image: "images/ChessOpenings.png",
        dataTestId: "chess-openings-card",
    },
    {
        name: 'Партии',
        description: 'База знаменитых партий',
        id: 6,
        link: '/chess-games',
        accessedRoles: ['admin', 'coach', 'student'],
        image: "images/Games.png",
        dataTestId: "chess-games-card",
    },
    {
        name: 'Статистика',
        description: 'Ваша статистика по занятиям',
        id: 7,
        link: '/statistic',
        accessedRoles: ['student'],
        image: "images/Reports.png",
        dataTestId: "reports-card",
    },
    // {
    //     name: 'Темы для обучения',
    //     description: 'Создание, редактирование, просмотр текущих тем для обучения',
    //     id: 7,
    //     link: '/learning-topics',
    //     workInProgress: false,
    //     accessedRoles: ['admin', 'coach']
    // }
]